### ISSUE TITLE
How to use the R package?

### ISSUE THREAD

**Issue by JiahuaQu** [daynefiler/gnomadR#1]
Hello Dr. Filer,
Thank you for creating this R package to help connect to the gnomAD API. Is there any example or demo to show how to use this package?
I want to download all variant inforamtion in ~500 genes in batch, and wonder how to use this package.

**Comment by daynefiler** [comment]
Hi @JiahuaQu -- thank you for your interest! I am not currently working on this project because of the gnomAD API limits. I would suggest doing queries through UCSC. They recently updated their data to NOT filter gnomAD variants from their database and you should be able to pull down the data you need. UCSC Genome Browser uses the more-common SQL language for the queries; they are very straight forward to write. I have written a couple functions for querying UCSC [here](https://github.com/daynefiler/dlfUtils/blob/e3db545005058c57c82a49e258cf238eee60b550/R/geneticDataTools.R).

**Comment by JiahuaQu** [comment]
Dear Dr. Filer,

Because we want to extract all information from gnomAD, I’m not sure how to do it from UCSF.
Thanks for your function in GitHub, but I still don’t know how to use them. Sorry, I’m new to it.
Thank you very much.
